Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-11, with the labels that each got.

#364 Create LicenseManager for licensing staff.
  app/waf/package.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/index.ts
  app/waf/src/services/license.service.ts
  app/waf/test/unit/AdcStateCtrlr.unit.ts
  app/waf/test/unit/AuthedToken.unit.ts
  app/waf/test/unit/service.ASGManager.ts
  app/waf/test/unit/service.LicenseManager.ts
  app/waf/test/unit/service.OnboardingManager.ts
  app/waf/test/unit/utils.checkAndWait.ts
  app/waf/test/unit/utils.findByKey.ts
  app/waf/test/unit/utils.merge.ts
  app/waf/test/unit/utils.runWithTimer.ts
Labels: enhancement

#335 Use DO rpm instead of container
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/license.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.do.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/testsetup-helper.ts
  app/waf/test/unit/service.LicenseManager.ts
  app/waf/test/unit/service.OnboardingManager.ts
Labels: enhancement

#336 Fix the link of name to show some details about the instance
  app/portal/horizon/openstack_dashboard/dashboards/f5services/f5adc/tables.py
  app/portal/horizon/openstack_dashboard/dashboards/f5services/f5adc/templates/f5adc/_instance_vm_detail.html
  app/portal/horizon/openstack_dashboard/local/local_settings.py
Labels: bug

#358 Remove do container
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/do.service.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/unit/service.LicenseManager.ts
  app/waf/test/unit/service.OnboardingManager.ts
  deploy/appcluster.rc
  deploy/docker-compose.yml
Labels: enhancement

#368 Enable efk as installation option
  .DS_Store
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/declaration.controller.ts
  app/waf/src/repositories/common.ts
  app/waf/src/services/do.service.ts
  deploy/appcluster.rc
  deploy/docker-compose-efk.yml
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: enhancement

#359 Find back the AS3 error message for TrustProxy.
  deploy/docker-compose.yml
  deploy/docker/asg/Dockerfile
  deploy/docker/asg/usr/share/rest/node/src/infrastructure/restOperationNetworkHandler.js
Labels: enhancement

#367 Add docs for how to run ADCaaS as an app.
  docs/configuration.rst
  docs/index.rst
  docs/run-it.rst
Labels: document

#366 upload install keys and certs.
  app/waf/src/controllers/cert.controller.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/key.controller.ts
  app/waf/src/datasources/asg.datasource.json
  app/waf/src/datasources/bigip.datasource.json
  app/waf/src/models/cert.model.ts
  app/waf/src/models/index.ts
  app/waf/src/models/key.model.ts
  app/waf/src/repositories/cert.repository.ts
  app/waf/src/repositories/index.ts
  app/waf/src/repositories/key.repository.ts
  app/waf/src/services/asg.service.ts
  app/waf/src/services/bigip.service.ts
  app/waf/test/acceptance/cert.controller.acceptance.ts
  app/waf/test/acceptance/key.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#319 Add build process for the release files.
  .gitignore
  data/.gitignore
  scripts/build_dist.sh
  scripts/download_as3.sh
  scripts/download_asg_dependencies.sh
  scripts/download_do.sh
  scripts/start_all.sh
Labels: enhancement

#379 Remove console.log
  app/waf/src/controllers/certificate.controller.ts
  app/waf/src/controllers/tlsserver.controller.ts
Labels: bug

#381 Revise and refine doc
  docs/configuration.rst
  docs/delivery-mode.rst
  docs/devopstest.rst
  docs/openstack-prerequisites.rst
  docs/plug-play-wafpolicies.rst
  docs/run-it.rst
Labels: document
