Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-04, with the labels that each got.

#77 A workaround for globalThis issue
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/application.controller.ts
Labels: bug

#78 Regulating test folders.
  app/waf/test/acceptance/mock.selftest.controller.acceptance.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.base.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.selftest.controller.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/rest.helpers.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement

#79 Regulating stub/restore logging for testing.
  app/waf/test/helpers/logging.helpers.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement

#81 reuse context.name as the request/response uuid
  app/waf/src/sequence.ts
Labels: bug, enhancement

#80 Build resource reponse body
  app/waf/src/controllers/common.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/schema.ts
Labels: enhancement

#66 Refactor Service resource API
  app/waf/src/controllers/service.controller.ts
  app/waf/src/models/service.model.ts
  app/waf/src/repositories/service.repository.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#85 Fix CI error in master branch
  app/waf/test/acceptance/service.controller.acceptance.ts
Labels: bug

#82 Retrieve tenant id from the request context.
  app/waf/.vscode/launch.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/keys.ts
  app/waf/src/sequence.ts
  app/waf/src/services/identity.service.ts
Labels: enhancement

#84 Move the identity definition of json body to services*.ts
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/services/identity.service.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#83 Many to many service policy
  app/waf/src/controllers/endpointpolicy.controller.ts
  app/waf/src/controllers/service.controller.ts
  app/waf/src/models/endpointpolicyassoc.model.ts
  app/waf/src/models/index.ts
  app/waf/src/models/service.model.ts
  app/waf/src/repositories/endpointpolicyassoc.repository.ts
  app/waf/src/repositories/index.ts
  app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#75 Revision pool, member, monitor APIs
  app/waf/src/controllers/monitor.controller.ts
  app/waf/src/controllers/pool.controller.ts
  app/waf/src/models/member.model.ts
  app/waf/src/models/monitor.model.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/repositories/member.repository.ts
  app/waf/src/repositories/monitor.repository.ts
  app/waf/src/repositories/pool.repository.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#87 add pool-monitor many to many
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/poolmonitorassc.controller.ts
  app/waf/src/models/index.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/models/poolmonitorassoc.model.ts
  app/waf/src/repositories/index.ts
  app/waf/src/repositories/poolmonitorassoc.repository.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#92 Fix reponse body of some resources
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/pool.controller.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
Labels: enhancement

#96 Refactor the action/condition/rule/endpointpolicy
  app/waf/src/controllers/endpointpolicy.controller.ts
  app/waf/src/controllers/rule.controller.ts
  app/waf/src/models/action.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/models/condition.model.ts
  app/waf/src/models/endpointpolicy.model.ts
  app/waf/src/models/rule.model.ts
  app/waf/src/repositories/action.repository.ts
  app/waf/src/repositories/condition.repository.ts
  app/waf/src/repositories/endpointpolicy.repository.ts
  app/waf/src/repositories/rule.repository.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#97 Adjust implementation detail for later calls.
  app/waf/src/services/compute.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#100 modify based on the review suggestions
  app/waf/src/models/action.model.ts
  app/waf/src/models/condition.model.ts
  app/waf/src/models/endpointpolicy.model.ts
  app/waf/src/models/rule.model.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#101 Use tenantId instead of tenantName.
  app/waf/.vscode/launch.json
  app/waf/src/services/identity.service.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#98 Update model specs which bases vm creation.
  app/waf/src/models/adc.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#103 Refactor WAF policy API
  app/waf/src/controllers/wafpolicy.controller.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/models/wafpolicy.model.ts
  app/waf/src/repositories/wafpolicy.repository.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#102 Change keepAdminTokenAlive to solveAdminToken.
  app/waf/src/application.ts
  app/waf/src/index.ts
  app/waf/src/services/identity.service.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#105 Fix issue of adminToken not authorized in network/compute.
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/network.service.ts
Labels: bug

#106 Collect auth token related operations into AuthedToken class.
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#90 Launch api spec design and code frame.
  app/waf/.vscode/launch.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/keys.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/sequence.ts
  app/waf/src/services/identity.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/sequence.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#108 Handle regioname and interface public
  app/waf/.vscode/launch.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: enhancement

#114 Cap nyc version until node-coveralls can support nyc 14
  app/waf/package.json
Labels: bug

#112 Add a brief introduction to dev, test, prod process.
  deploy/README.md
Labels: document

#113 Check vm is ready to onboarding.
  app/waf/.vscode/launch.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/bigip.datasource.json
  app/waf/src/datasources/bigip.datasource.ts
  app/waf/src/datasources/index.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/index.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement
