Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-07, with the labels that each got.

#198 Service resource API validation
  app/waf/src/controllers/schema.ts
  app/waf/src/models/common.model.ts
  app/waf/src/models/service.model.ts
  app/waf/src/utils.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
Labels: enhancement

#201 Refine patch resource API
  app/waf/src/controllers/endpointpolicy.controller.ts
  app/waf/src/controllers/monitor.controller.ts
  app/waf/src/controllers/pool.controller.ts
  app/waf/src/controllers/rule.controller.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
Labels: bug

#215 Fix openapi issue caused by package changes.
  app/waf/src/controllers/schema.ts
Labels: bug

#214 Fix the issue of array type model property's update issue.
  app/waf/src/models/service.model.ts
  app/waf/src/repositories/common.ts
Labels: bug

#200 Add floating ip support.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/models/adc.model.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/acceptance/sequence.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/database.helpers.ts
  app/waf/test/helpers/test-helper.ts
  deploy/appcluster.rc
Labels: enhancement

#199 Support blacklist property validation for service resource
  app/waf/src/controllers/schema.ts
  app/waf/src/models/common.model.ts
  app/waf/src/models/service.model.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#203 Validate reference id of service resource
  app/waf/src/controllers/service.controller.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
Labels: enhancement

#173 Create newman test
  test/.gitignore
  test/onboard-collection.json
  test/os-queens-environment.json
  test/test_all.sh
Labels: enhancement

#224 Improve newman test prepare stage
  deploy/appcluster.rc
  test/onboard-collection.json
  test/os-queens-environment.json
Labels: enhancement

#235 Need to update DO endpoint after we use DO 1.5.0
  deploy/appcluster.rc
Labels: bug

#222 Remove the multiple-line log output.
  app/waf/src/controllers/adc.controller.ts
Labels: bug

#231 Add dependency files to repo.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/helpers/test-helper.ts
  dependencies/ASGExtensions/TrustedASMPolicies-1.0.5-0004.noarch.rpm
  dependencies/ASGExtensions/TrustedDevices-1.3.0-0002.noarch.rpm
  dependencies/ASGExtensions/TrustedExtensions-1.0.1-0001.noarch.rpm
  dependencies/ASGExtensions/TrustedProxy-1.0.1-0002.noarch.rpm
  dependencies/f5-declarative-onboarding-1.5.0-11.noarch.rpm
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/download_asg_dependencies.sh
  scripts/download_do.sh
  scripts/start_all.sh
Labels: enhancement

#186 Find ep from usertoken
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/declaration.controller.ts
  app/waf/src/keys.ts
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
Labels: enhancement

#245 Fix the issue caused by promise.then.finally.
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: bug

#242 Add as3 rpm package and download script to repo.
  app/waf/src/services/asg.service.ts
  dependencies/.gitignore
  dependencies/ASGExtensions/TrustedASMPolicies-1.0.5-0004.noarch.rpm
  dependencies/ASGExtensions/TrustedDevices-1.3.0-0002.noarch.rpm
  dependencies/ASGExtensions/TrustedExtensions-1.0.1-0001.noarch.rpm
  dependencies/ASGExtensions/TrustedProxy-1.0.1-0002.noarch.rpm
  dependencies/f5-declarative-onboarding-1.5.0-11.noarch.rpm
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/download_as3.sh
  scripts/start_all.sh
Labels: enhancement

#220 Refactor the create / setup api.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/do.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#246 error terminate using checkAndWait for isTrusted
  app/waf/src/controllers/adc.controller.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#247 Ignore dependency rpms
  dependencies/.gitignore
  scripts/download_asg_dependencies.sh
Labels: bug

#253 use both the adc name and uuid for nova vm's name
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/models/common.model.ts
Labels: enhancement

#254 Update README.md
  CONTRIBUTING.md
  README.md
Labels: document

#258 add requestId in logger names
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/declaration.controller.ts
  app/waf/src/repositories/action.repository.ts
  app/waf/src/repositories/adc.repository.ts
  app/waf/src/repositories/application.repository.ts
  app/waf/src/repositories/common.ts
  app/waf/src/repositories/condition.repository.ts
  app/waf/src/repositories/declaration.repository.ts
  app/waf/src/repositories/endpointpolicy.repository.ts
  app/waf/src/repositories/member.repository.ts
  app/waf/src/repositories/monitor.repository.ts
  app/waf/src/repositories/pool.repository.ts
  app/waf/src/repositories/rule.repository.ts
  app/waf/src/repositories/service.repository.ts
  app/waf/src/repositories/wafpolicy.repository.ts
  app/waf/src/sequence.ts
  app/waf/src/services/asg.service.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/network.service.ts
Labels: enhancement

#241 Add end-to-end WAF test
  test/onboard-collection.json
  test/os-queens-environment.json
Labels: enhancement

#262 Move pg data directory to data to make config data keepable.
  app/waf/.gitignore
  app/waf/src/index.ts
  data/.gitignore
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: enhancement

#249 enable https for adcaas
  app/waf/index.js
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: enhancement
