Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-05, with the labels that each got.

#116 change monitor for multi-tenancy
  app/waf/.gitignore
  app/waf/.vscode/settings.json
  app/waf/.vscode/tasks.json
  app/waf/src/controllers/monitor.controller.ts
  app/waf/src/repositories/common.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#109 Trust ADC hardware
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/index.ts
  app/waf/src/datasources/trusteddevice.datasource.json
  app/waf/src/datasources/trusteddevice.datasource.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/services/index.ts
  app/waf/src/services/trusteddevice.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#104 AS3 translation
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/declaration.controller.ts
  app/waf/src/controllers/index.ts
  app/waf/src/models/action.model.ts
  app/waf/src/models/application.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/models/common.model.ts
  app/waf/src/models/condition.model.ts
  app/waf/src/models/declaration.model.ts
  app/waf/src/models/endpointpolicy.model.ts
  app/waf/src/models/member.model.ts
  app/waf/src/models/monitor.model.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/models/rule.model.ts
  app/waf/src/models/service.model.ts
  app/waf/src/models/wafpolicy.model.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#117 Add onboarding logic and tests.
  app/waf/.vscode/launch.json
  app/waf/package.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/bigip.datasource.json
  app/waf/src/models/adc.model.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.do.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/database.helpers.ts
  app/waf/test/helpers/test-helper.ts
  deploy/appcluster.rc
Labels: enhancement

#122 add mutltitenancy to poolmonitorassoc
  app/waf/src/controllers/poolmonitorassc.controller.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
Labels: enhancement

#121 Fix 500 error when auth* fail; Regulate the auth* related logic.
  app/waf/src/components.ts
  app/waf/src/keys.ts
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
Labels: bug, enhancement

#120 Add utils.ts and waitAndCheck function.
  app/waf/package.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/sequence.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/utils.ts
Labels: enhancement

#123 Add ntp onboarding.
  app/waf/src/services/do.service.ts
Labels: enhancement

#128 Report the errors happen during onboarding body assembling.
  app/waf/src/services/do.service.ts
Labels: enhancement

#126 Implement the merge function used to merge object incursively.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/utils.ts
Labels: enhancement

#130 Add license check control.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
Labels: enhancement

#127 Do create and setup bigip VE asynchronously.
  app/waf/src/controllers/adc.controller.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#125 Regulate database environment variables and migration.
  app/waf/src/datasources/db.datasource.ts
  app/waf/src/index.ts
  app/waf/test/unit/application.unit.ts
  deploy/appcluster.rc
Labels: bug

#129 Add and implement the lastErr feature.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/models/adc.model.ts
Labels: enhancement

#132 Fix issue of probing a hostname in docker running mode.
  app/waf/package.json
  app/waf/src/index.ts
  app/waf/src/services/bigip.service.ts
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: bug, enhancement

#131 Fix the leaks when onboarding error.
  app/waf/src/controllers/adc.controller.ts
Labels: bug

#134 Fix the issue of travis caused by dbReady check.
  scripts/publish_api_ref.sh
Labels: bug

#135 Set configsync IP via DO
  app/waf/src/services/do.service.ts
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: enhancement

#138 Use f5-do-container:1.4.0-1 which support multiple tasks.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/do.service.ts
  app/waf/test/fixtures/controllers/mocks/mock.do.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  deploy/docker-compose.yml
Labels: bug, enhancement

#140 Enable multi-tenancy support for Application resource
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/base.controller.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/service.controller.ts
  app/waf/src/repositories/common.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
Labels: enhancement

#142 Enable multi-tenancy support for ADC resource
  app/waf/src/controllers/adc.controller.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#145 wafpolicy multiple-tenant enhancement
  app/waf/src/controllers/wafpolicy.controller.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
Labels: enhancement

#144 Enable multi-tenancy support for Declaration resource
  app/waf/src/controllers/declaration.controller.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
Labels: enhancement

#147 Set DB default value
  app/waf/src/datasources/db.datasource.json
  app/waf/src/index.ts
Labels: enhancement

#148 Set default interval of checkAndWait()
  app/waf/src/utils.ts
Labels: enhancement

#150 Combine all duplicate environment setup/teardown code.
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/acceptance/sequence.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement

#139 Implement the adc deletion.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/models/adc.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/do.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/database.helpers.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement

#118 Build trust relation against VE instance
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/src/services/trusteddevice.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  deploy/appcluster.rc
  scripts/download_asg_dependencies.sh
Labels: enhancement

#152 Rename TrustDevice* to ASG to reuse it as Trust* Service.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/asg.datasource.json
  app/waf/src/datasources/asg.datasource.ts
  app/waf/src/datasources/index.ts
  app/waf/src/datasources/trusteddevice.datasource.ts
  app/waf/src/services/asg.service.ts
  app/waf/src/services/index.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#155 Save trusted device id
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/models/adc.model.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: bug

#136 Add more precise control on checking create/setup done.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/bigip.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
Labels: enhancement

#158 Fix the issue of travis failure caused by typescript -> 3.5.1.
  app/waf/package.json
Labels: bug

#111 Install AS3 RPM on ADC device
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/datasources/asg.datasource.json
  app/waf/src/services/asg.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#159 Adjust trust API error condition
  app/waf/src/services/asg.service.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#162 fix findById bug
  app/waf/src/repositories/common.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: bug

#157 uploading wafpolicy file from an URL to a target F5 device and check its state
  app/waf/src/controllers/wafpolicy.controller.ts
  app/waf/src/datasources/asg.datasource.json
  app/waf/src/models/index.ts
  app/waf/src/models/wafpolicy.model.ts
  app/waf/src/models/wafpolicyondevice.model.ts
  app/waf/src/services/asg.service.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
Labels: enhancement

#161 To be compatible with v2.1's different cases.
  app/waf/src/services/identity.service.ts
Labels: bug
