Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-09, with the labels that each got.

#311 vpn operation has no relation with product, only for test.
  .travis.yml
  test/vpn/PulseClient_x86_64.sh.patch
  test/vpn/vpn.crt
  test/vpn/vpn_connect.sh
  test/vpn/vpn_install.sh
Labels: enhancement

#313 Move and convert the .md files to .rst under docs.
  app/waf/pnp_waf_policy.md
  app/waf/some-prerequisites.md
  deploy/README.md
  docs/configuration.rst
  docs/delivery-mode.rst
  docs/devopstest.rst
  docs/index.rst
  docs/openstack-prerequisites.rst
  docs/plug-play-wafpolicies.rst
  scripts/README.md
Labels: document

#317 Fix npm test error because of npm package updates.
  app/waf/test/helpers/testsetup-helper.ts
Labels: bug

#316 Update the staging link to prodcution link.
  README.md
Labels: document

#310 Integrate portal container into docker-compose.
  app/waf/index.js
  deploy/appcluster.rc
  deploy/docker-compose.yml
  scripts/generate_certs.sh
Labels: enhancement

#318 Add docs denpendency file _templates/layout.html
  docs/_templates/layout.html
Labels: document

#324 Add start and end message for performance analysis.
  app/waf/src/controllers/adc.controller.ts
Labels: enhancement

#326 Fix several issues of portal.
  app/portal/Dockerfile
  app/portal/horizon/openstack_dashboard/api/f5wafaas.py
  app/portal/horizon/openstack_dashboard/dashboards/f5services/static/dashboard/f5services/workflow/launch-instance/launch-instance-model.service.js
  app/portal/horizon/openstack_dashboard/local/.gitignore
  app/portal/horizon/openstack_dashboard/local/.secret_key_store
  app/portal/horizon/openstack_dashboard/local/local_settings.py
  app/portal/scripts/venv.rc
  app/waf/index.js
  scripts/generate_certs.sh
  scripts/start_all.sh
Labels: bug

#325 Calculate function execution time.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/utils.ts
  app/waf/test/unit/utils.runWithTimer.ts
Labels: enhancement

#328 Fix flavor and image issue when flavor/image deleted.
  app/portal/horizon/.vscode/launch.json
  app/portal/horizon/openstack_dashboard/dashboards/f5services/f5adc/views.py
  deploy/appcluster.rc
Labels: bug

#329 Use floatingip if exists for multiple tenant case.
  app/waf/src/controllers/adc.controller.ts
Labels: enhancement

#323 pool/member/monitor validation
  app/waf/src/models/member.model.ts
  app/waf/src/models/monitor.model.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/models/service.model.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
Labels: enhancement

#290 Save onboarding error message
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/services/do.service.ts
  app/waf/src/utils.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/helpers/logging.helpers.ts
  app/waf/test/unit/service.OnboardingManager.ts
  app/waf/test/unit/utils.checkAndWait.ts
Labels: enhancement

#280 Remove duplicated rule API
  app/waf/src/controllers/endpointpolicy.controller.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
Labels: enhancement

#281 Refactor monitor many-to-many API
  app/waf/src/controllers/declaration.controller.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/membermonitorassc.controller.ts
  app/waf/src/controllers/monitor.controller.ts
  app/waf/src/controllers/pool.controller.ts
  app/waf/src/controllers/poolmonitorassc.controller.ts
  app/waf/src/repositories/poolmonitorassoc.repository.ts
  app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
  test/onboard-collection.json
Labels: enhancement

#339 Update test script
  test/onboard-collection.json
Labels: enhancement

#342 TMA - remove credential information
  deploy/appcluster.rc
Labels: enhancement
