Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-08, with the labels that each got.

#251 Make password generation configurable.
  app/waf/package.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement

#243 Fix err state cannot be reclaimed and add its unit test.
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/utils.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/database.helpers.ts
  app/waf/test/unit/AdcStateCtrlr.unit.ts
  app/waf/test/unit/utils.merge.ts
Labels: bug

#225 Refactor acceptance test framework.
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicyassoc.controller.acceptance.ts
  app/waf/test/acceptance/home-page.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/acceptance/membermonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/mock.selftest.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/acceptance/ping.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/acceptance/poolmonitorassoc.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/acceptance/sequence.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/acceptance/tenantassoc.controller.acceptance.ts
  app/waf/test/acceptance/unkown.path.acceptance.ts
  app/waf/test/acceptance/wafpolicy.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mocks/mock.asg.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.bigip.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.do.controller.ts
  app/waf/test/fixtures/controllers/mocks/mock.openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/database.helpers.ts
  app/waf/test/helpers/testsetup-helper.ts
  app/waf/test/unit/AdcStateCtrlr.unit.ts
Labels: enhancement

#282 Access ping API without keystone token
  app/waf/src/controllers/ping.controller.ts
  app/waf/src/index.ts
  app/waf/src/sequence.ts
  app/waf/test/acceptance/ping.controller.acceptance.ts
  scripts/publish_api_ref.sh
Labels: enhancement

#271 Verify onboarding service and add unit test.
  app/waf/src/services/do.service.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/unit/service.OnboardingManager.ts
Labels: enhancement

#270 Add unit test to AuthedToken.
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/testsetup-helper.ts
  app/waf/test/unit/AdcStateCtrlr.unit.ts
  app/waf/test/unit/AuthedToken.unit.ts
Labels: enhancement

#272 Verify and unit test the service ASGManager.
  app/waf/src/services/asg.service.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/unit/service.ASGManager.ts
Labels: enhancement

#285 Fix onboarding unit test error.
  app/waf/test/fixtures/datasources/testrest.datasource.ts
Labels: bug

#229 Store asg data outside of container through mounting volumes.
  deploy/docker-compose.yml
  scripts/start_all.sh
Labels: enhancement

#287 Update newman test
  test/onboard-collection.json
  test/os-queens-environment.json
Labels: enhancement

#275 Connect to Beijing lab vpn
  .travis.yml
  scripts/PulseClient_x86_64.sh.patch
  scripts/vpn.crt
  scripts/vpn_connect.sh
  scripts/vpn_install.sh
Labels: enhancement

#286 Rename docker image repo to f5-openstack-services
  app/waf/Dockerfile
  deploy/README.md
  deploy/docker-compose.yml
Labels: enhancement

#279 Add ADCaaS release introduction.
  scripts/README.md
Labels: document

#293 Fix ADC networks validation
  app/waf/src/models/adc.model.ts
Labels: bug

#277 Endpointpolicy API validation
  app/waf/src/controllers/rule.controller.ts
  app/waf/src/models/action.model.ts
  app/waf/src/models/condition.model.ts
  app/waf/src/models/rule.model.ts
  app/waf/src/models/wafpolicy.model.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
Labels: enhancement

#294 Add Travis job to publish document
  .travis.yml
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/deploy-docs.sh
  docs/docker-docs.sh
  docs/index.rst
  docs/test-docs.sh
Labels: document

#256 Fix deploy job
  scripts/publish_api_ref.sh
Labels: enhancement

#289 update logging in README.md
  deploy/README.md
Labels: document

#297 Rename fluentd image
  deploy/docker-compose.yml
  deploy/docker/fluent/Dockerfile
Labels: enhancement

#273 editing of the readme
  README.md
Labels: document

#298 Rename portal image
  app/portal/Dockerfile
  deploy/docker-compose.yml
Labels: enhancement

#299 Rename app image
  app/waf/Dockerfile
  deploy/docker-compose.yml
Labels: enhancement

#301 Compile typescript during docker build
  app/waf/Dockerfile
Labels: enhancement

#302 Publish docker image
  .travis.yml
  scripts/publish_image.sh
Labels: enhancement

#304 Order ports beginning with mgmt.
  app/waf/src/controllers/adc.controller.ts
Labels: bug

#268 Regulate cert generation to ignore it when !WAF_ENABLE_HTTPS
  deploy/appcluster.rc
  scripts/generate_certs.sh
  scripts/start_all.sh
Labels: enhancement

#300 Concrete ASG image version
  deploy/docker-compose.yml
Labels: enhancement

#288 Rename WAFAAS to ADCAAS
  CONTRIBUTING.md
  README.md
  app/waf/index.js
  deploy/README.md
  deploy/appcluster.rc
  deploy/docker-compose.yml
  deploy/unset-wafaas-environs.rc
  scripts/README.md
  scripts/generate_certs.sh
Labels: enhancement
