Repository F5Networks/f5-adcaas-openstack, pull requests merged in 2019-03, with the labels that each got.

#36 Deploy application configuration to AS3 gateway
  app/waf/.DS_Store
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/ping.controller.ts
  app/waf/src/datasources/as-3.datasource.json
  app/waf/src/models/adc.model.ts
  app/waf/src/models/application.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/models/index.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/models/service.model.ts
  app/waf/src/models/wafpolicy.model.ts
  app/waf/src/services/as3.service.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/ping.controller.acceptance.ts
  app/waf/test/acceptance/pool.contoller.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#41 Pool has many members
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/pool.controller.ts
  app/waf/src/models/member.model.ts
  app/waf/src/models/pool.model.ts
  app/waf/src/repositories/pool.repository.ts
  app/waf/src/sequence.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/member.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#45 Disable response log
  app/waf/src/sequence.ts
Labels: bug

#40 Refactor ADC resource APIs
  app/waf/src/application.ts
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/schema.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/models/common.model.ts
  app/waf/src/models/index.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#42 App has many sv
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/service.controller.ts
  app/waf/src/models/application.model.ts
  app/waf/src/models/service.model.ts
  app/waf/src/repositories/application.repository.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/service.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#44 Publish API specification
  .travis.yml
  scripts/publish_api_ref.sh
Labels: document

#50 Fix api doc deploy script
  scripts/publish_api_ref.sh
Labels: bug

#51 Do not cleanup before deploy api doc
  .travis.yml
Labels: bug

#53 conform to the naming conversion and reuse the commonEntity base class
  app/waf/src/controllers/rule.controller.ts
  app/waf/src/models/action.model.ts
  app/waf/src/models/condition.model.ts
  app/waf/test/acceptance/action.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
Labels: enhancement

#47 add monitor resource
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/monitor.controller.ts
  app/waf/src/models/index.ts
  app/waf/src/models/monitor.model.ts
  app/waf/src/repositories/index.ts
  app/waf/src/repositories/monitor.repository.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#55 Refactor API schema generating code
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/schema.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/models/common.model.ts
Labels: enhancement

#56 Implement tenantId property
  app/waf/src/models/common.model.ts
Labels: enhancement

#61 Import property key from loopback
  app/waf/src/controllers/schema.ts
Labels: enhancement

#63 Fix Travis CI deploy error
  scripts/publish_api_ref.sh
Labels: bug

#60 add todo item.
  app/waf/src/models/as3.model.ts
Labels: enhancement

#68 Fix Travis CI error
  scripts/publish_api_ref.sh
Labels: bug

#64 integrating with openstack keystone/nova/neutron
  app/waf/.vscode/launch.json
  app/waf/.vscode/tasks.json
  app/waf/src/application.ts
  app/waf/src/components.ts
  app/waf/src/datasources/index.ts
  app/waf/src/datasources/openstack.datasource.json
  app/waf/src/datasources/openstack.datasource.ts
  app/waf/src/index.ts
  app/waf/src/log4ts.ts
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/index.ts
  app/waf/src/services/network.service.ts
  app/waf/test/acceptance/mock.selftest.controller.acceptance.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/mock.openstack.controller.ts
  app/waf/test/fixtures/controllers/mock.selftest.controller.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
  app/waf/test/fixtures/datasources/testrest.datasource.ts
  app/waf/test/helpers/logging.helpers.ts
  app/waf/test/helpers/rest.helpers.ts
  app/waf/test/helpers/test-helper.ts
  app/waf/tslint.build.json
  deploy/appcluster.rc
  deploy/unset-wafaas-environs.rc
Labels: enhancement

#67 A workaround for response log
  app/waf/src/sequence.ts
Labels: bug

#69 fix the bug of logResponse exception.
  app/waf/src/sequence.ts
Labels: bug

#70 Auto-generate resource id and timestamp
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/models/common.model.ts
  app/waf/src/repositories/adc.repository.ts
  app/waf/src/repositories/common.ts
  app/waf/src/repositories/index.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
Labels: enhancement

#59 one policy has many rules
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/endpointpolicy.controller.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/models/endpointpolicy.model.ts
  app/waf/src/models/rule.model.ts
  app/waf/src/repositories/endpointpolicy.repository.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/condition.controller.acceptance.ts
  app/waf/test/acceptance/endpointpolicy.controller.acceptance.ts
  app/waf/test/acceptance/monitor.controller.acceptance.ts
  app/waf/test/acceptance/rule.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#57 Refactor Application resource API
  app/waf/src/controllers/application.controller.ts
  app/waf/src/models/application.model.ts
  app/waf/src/models/as3.model.ts
  app/waf/src/repositories/application.repository.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#72 Remove process.env.TEST_OPENSTACK_INTEGRATION
  app/waf/.vscode/launch.json
  app/waf/src/application.ts
  app/waf/src/components.ts
  app/waf/test/acceptance/mock.selftest.controller.acceptance.ts
  app/waf/test/acceptance/openstack.controller.acceptance.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
  app/waf/test/helpers/rest.helpers.ts
Labels: enhancement

#74 Another implement of API response
  app/waf/package.json
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/common.ts
  app/waf/src/controllers/index.ts
  app/waf/src/controllers/schema.ts
  app/waf/src/models/adc.model.ts
  app/waf/src/models/common.model.ts
Labels: enhancement

#52 Implement many-to-many relation between ADC and Tenant
  app/waf/src/controllers/adc.controller.ts
  app/waf/src/controllers/application.controller.ts
  app/waf/src/controllers/tenantassoc.controller.ts
  app/waf/src/models/common.model.ts
  app/waf/src/models/tenantassoc.model.ts
  app/waf/src/repositories/tenantassoc.repository.ts
  app/waf/test/acceptance/adc.controller.acceptance.ts
  app/waf/test/acceptance/application.controller.acceptance.ts
  app/waf/test/acceptance/tenantassoc.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#54 Implement AS3 Declaration resource
  app/waf/src/controllers/application.controller.ts
  app/waf/src/models/application.model.ts
  app/waf/src/models/declaration.model.ts
  app/waf/src/models/index.ts
  app/waf/src/repositories/application.repository.ts
  app/waf/src/repositories/declaration.repository.ts
  app/waf/src/repositories/index.ts
  app/waf/test/acceptance/declaration.controller.acceptance.ts
  app/waf/test/helpers/database.helpers.ts
Labels: enhancement

#73 Regulate binding keys to keys.ts
  app/waf/src/application.ts
  app/waf/src/components.ts
  app/waf/src/keys.ts
  app/waf/src/sequence.ts
  app/waf/src/services/compute.service.ts
  app/waf/src/services/identity.service.ts
  app/waf/src/services/network.service.ts
  app/waf/test/fixtures/controllers/openstack.controller.ts
  app/waf/test/helpers/test-helper.ts
Labels: enhancement
